// Generated by project-provider-summary; do not edit.
export const expectedProviderSummarySHA256 = "sha256:0c1d355a8cb6ff09373dadd050096ce81fb8cd3e2e70c1248598edf0ae720d96";
export const expectedProviderSummaryURL = "/lab-data/provider-summary-0c1d355a8cb6ff09373dadd050096ce81fb8cd3e2e70c1248598edf0ae720d96.json";
