package main

import (
	"flag"
	"fmt"
	"os"

	"github.com/bkmashiro/agent-python-runtime/research/labview"
)

func run(inputPath, outputPath, identityOutputPath string) error {
	if inputPath == "" || outputPath == "" || identityOutputPath == "" {
		return fmt.Errorf("input, output, and identity-output are required")
	}
	raw, err := os.ReadFile(inputPath)
	if err != nil {
		return err
	}
	snapshot, err := labview.BuildUnifiedSnapshot(raw)
	if err != nil {
		return err
	}
	encoded, err := labview.EncodeUnifiedSnapshot(snapshot)
	if err != nil {
		return err
	}
	if err := os.WriteFile(outputPath, encoded, 0o644); err != nil {
		return err
	}
	identity := fmt.Sprintf("// Generated by project-unified; do not edit.\nexport const expectedUnifiedSnapshotIdentity = %q;\n", snapshot.Identity)
	return os.WriteFile(identityOutputPath, []byte(identity), 0o644)
}

func main() {
	input := flag.String("input", "", "unified mechanism campaign evidence")
	output := flag.String("output", "", "public unified Lab snapshot")
	identityOutput := flag.String("identity-output", "", "generated TypeScript identity")
	flag.Parse()
	if err := run(*input, *output, *identityOutput); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
