package main

import (
	"flag"
	"fmt"
	"os"

	"github.com/bkmashiro/agent-python-runtime/research/labview"
)

func read(path string) ([]byte, error) {
	if path == "" {
		return nil, fmt.Errorf("latest Lab input path is required")
	}
	return os.ReadFile(path)
}

func run(paths map[string]string, outputPath, identityOutputPath string) error {
	inputs := map[string][]byte{}
	for name, path := range paths {
		raw, err := read(path)
		if err != nil {
			return fmt.Errorf("read %s: %w", name, err)
		}
		inputs[name] = raw
	}
	snapshot, err := labview.BuildLatestSnapshot(labview.LatestInputs{
		SourcePrefixContract: inputs["source-prefix-contract"],
		SourcePrefixEvidence: inputs["source-prefix-evidence"],
		CampaignManifest:     inputs["campaign-manifest"],
		CampaignProjection:   inputs["campaign-projection"],
		SemanticPredispatch:  inputs["semantic-predispatch"],
		SemanticReuse:        inputs["semantic-reuse"],
		COWGrowable:          inputs["cow-growable"],
		ColdIO:               inputs["cold-io"],
		Composable:           inputs["composable"],
	})
	if err != nil {
		return err
	}
	encoded, err := labview.EncodeLatestSnapshot(snapshot)
	if err != nil {
		return err
	}
	if outputPath == "" {
		return fmt.Errorf("latest Lab output path is required")
	}
	if err := os.WriteFile(outputPath, encoded, 0o644); err != nil {
		return err
	}
	if identityOutputPath == "" {
		return nil
	}
	identitySource := fmt.Sprintf("// Generated by project-latest; do not edit.\nexport const expectedLatestSnapshotIdentity = %q;\n", snapshot.Identity)
	return os.WriteFile(identityOutputPath, []byte(identitySource), 0o644)
}

func main() {
	flags := map[string]*string{}
	for _, name := range []string{"source-prefix-contract", "source-prefix-evidence", "campaign-manifest", "campaign-projection", "semantic-predispatch", "semantic-reuse", "cow-growable", "cold-io", "composable"} {
		flags[name] = flag.String(name, "", name+" JSON")
	}
	output := flag.String("output", "", "latest Lab snapshot output JSON")
	identityOutput := flag.String("identity-output", "", "generated TypeScript identity output")
	flag.Parse()
	paths := map[string]string{}
	for name, value := range flags {
		paths[name] = *value
	}
	if err := run(paths, *output, *identityOutput); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
