package main

import (
	"flag"
	"fmt"
	"os"

	"github.com/bkmashiro/agent-python-runtime/research/labview"
)

func read(path string) ([]byte, error) {
	if path == "" {
		return nil, fmt.Errorf("latest Lab input path is required")
	}
	return os.ReadFile(path)
}

func run(contractPath, overlapPath, censusPath, manifestPath, campaignPath, outputPath, identityOutputPath string) error {
	contract, err := read(contractPath)
	if err != nil {
		return err
	}
	overlap, err := read(overlapPath)
	if err != nil {
		return err
	}
	census, err := read(censusPath)
	if err != nil {
		return err
	}
	manifest, err := read(manifestPath)
	if err != nil {
		return err
	}
	campaign, err := read(campaignPath)
	if err != nil {
		return err
	}
	snapshot, err := labview.BuildLatestSnapshot(labview.LatestInputs{
		SourcePrefixContract: contract,
		SourcePrefixEvidence: overlap,
		SourcePrefixCensus:   census,
		CampaignManifest:     manifest,
		CampaignProjection:   campaign,
	})
	if err != nil {
		return err
	}
	encoded, err := labview.EncodeLatestSnapshot(snapshot)
	if err != nil {
		return err
	}
	if outputPath == "" {
		return fmt.Errorf("latest Lab output path is required")
	}
	if err := os.WriteFile(outputPath, encoded, 0o644); err != nil {
		return err
	}
	if identityOutputPath == "" {
		return nil
	}
	identitySource := fmt.Sprintf("// Generated by project-latest; do not edit.\nexport const expectedLatestSnapshotIdentity = %q;\n", snapshot.Identity)
	return os.WriteFile(identityOutputPath, []byte(identitySource), 0o644)
}

func main() {
	contract := flag.String("source-prefix-contract", "", "source-prefix contract JSON")
	overlap := flag.String("source-prefix-evidence", "", "source-prefix evidence JSON")
	census := flag.String("source-prefix-census", "", "source-prefix census JSON")
	manifest := flag.String("campaign-manifest", "", "accepted campaign manifest JSON")
	campaign := flag.String("campaign-projection", "", "transparent campaign public projection JSON")
	output := flag.String("output", "", "latest Lab snapshot output JSON")
	identityOutput := flag.String("identity-output", "", "generated TypeScript identity output")
	flag.Parse()
	if err := run(*contract, *overlap, *census, *manifest, *campaign, *output, *identityOutput); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
